### ISSUE TITLE
What URL should be reported?

### ISSUE THREAD

**Issue by yoavweiss** [yoavweiss/subresource-reporting#3]
ResourceTiming currently reports the [request's URL](https://fetch.spec.whatwg.org/#concept-request-url), which is the first URL in the redirect chain (the one that the site initiated). 

We could also opt to report the last URL in the redirect chain (the [response URL](https://fetch.spec.whatwg.org/#concept-response-url)). I *believe* the response URL is already exposed to Service Workers. At the same time, I'm not sure there's a strong use case for it, and folks may find it confusing. ("How did this URL get here?")

So, I think the request URL is the way to go, unless folks find use cases for the response one.

**Comment by MrMarvin** [comment]
Without much context, what URL is reported in other reporting mechanisms such as CSP violations? I'd think that request URL is the generally more useful as thats a direct reflection of whats on the page, so using it to both resource timing and subresource reporting makes for a more complete overall picture.

**Comment by yoavweiss** [comment]
> what URL is reported in other reporting mechanisms such as CSP violations?

CSP reports the request URL, as it doesn't have a response at the point in which reporting happens (nor ever, when in enforcement mode).

**Comment by yoavweiss** [comment]
Closing, as I think I answered my own question (and no one has use cases that reach a different conclusion).
